apiVersion: v1
kind: Service
metadata:
  name: django-app-qa-svc
  namespace: default
spec:
  selector:
    app: django-app
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8000
      name: http
    - port: 443
      protocol: TCP
      name: https
  type: NodePort
