name: Validate Terraform

on:
  pull_request:
    paths:
    - 'terraform/**'
  workflow_dispatch:

jobs:
  validate-terraform:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component: ['base', 'django-qa']
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      - name: terraform init
        working-directory: "terraform/${{ matrix.component }}"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform init
      - name: terraform validate
        working-directory: "terraform/${{ matrix.component }}"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform validate